made changes to display the phone number under SignIn Information
episphere/connectApp pull request #490
Opened 2023-03-23 20:38 UTC by ramavavi

Git hub Issue: https://github.com/episphere/connectApp/issues/349

Under the Sign In Information, it now displays the phone number or email used while logging in.

2023-03-24 13:27 UTC, Gbarra9 requested changes

2023-03-24 13:27 UTC, Gbarra9 commented on js/pages/settings.js
> +    // write conditions for email, phone or empty
This code comment in my opinion is not needed.

2023-03-24 13:27 UTC, Gbarra9 commented on js/pages/settings.js
> +    console.log("userData", userData)
This console log can be removed.

2023-03-24 13:56 UTC, anthonypetersen commented
please modify the PR, this can't go directly into production

2023-03-24 13:59 UTC, anthonypetersen requested changes
correct spelling of variable, change target branch of PR

2023-03-24 13:59 UTC, anthonypetersen commented on js/pages/settings.js
> +        signInInfornmationContent =
correct spelling

2023-03-31 14:29 UTC, anthonypetersen approved these changes

2023-03-31 16:17 UTC, merged