Consent versioning v0.02 nci
episphere/connectApp pull request #515
Opened 2023-04-20 16:24 UTC by ramavavi

Git hub issue: https://github.com/episphere/connectApp/issues/491

Changed the version1.0 for NCI HIPAA and Consent to Version0.02.

2023-04-20 16:25 UTC, anthonypetersen commented
I will review this today, but please wait to merge until I give the green light.

2023-04-20 16:27 UTC, ramavavi commented
Ok sure Tony, thank you.

2023-04-20 19:52 UTC, anthonypetersen requested changes

2023-04-20 19:52 UTC, anthonypetersen commented on js/pages/consent.js
> +    console.log
please remove

2023-04-20 20:20 UTC, anthonypetersen commented
Also need accompanying PDFs for these files (NCI versions at the very least)

2023-04-28 15:51 UTC, anthonypetersen commented
is this still needed? if not, please close

2023-06-20 16:15 UTC, closed without merging