Made changes in the MySamples Page for Marshfield_Issue
episphere/connectApp pull request #565
Opened 2023-06-05 13:55 UTC by ramavavi

The following Pull request (PR) addresses: https://github.com/episphere/connectApp/issues/548

Updates to the code:

1. Made changes to Locations and the timings.
2. Made a few edits under the heading How do I donate my samples?

2023-06-05 14:11 UTC, Gbarra9 commented on js/pages/samples.js
> +    howToDonate: 'The email we send you will contain a link to schedule an appointment. Simply click the link to schedule a time that is convenient for you to donate your samples.You can also  please
The email we send you will contain a link to schedule an appointment. Simply click the link to schedule a time that is convenient for you to donate your samples.You can also please call Marshfield Clinic Research Institute at 715-898-9444 to schedule an appointment, or a Connect team member will call you to schedule an appointment to donate your samples at a time that is convenient for you.
```suggestion
    howToDonate: 'The email we send you will contain a link to schedule an appointment. Simply click the link to schedule a time that is convenient for you to donate your samples.You can also call Marshfield Clinic Research Institute at 715-898-9444 to schedule an appointment, or a Connect team member will call you to schedule an appointment to donate your samples at a time that is convenient for you.',
```

I think from the [document]([Marshfield_Biospecimen Info Template for PWA_UpdatesMay2023.docx](https://github.com/episphere/connectApp/files/11432673/Marshfield_Biospecimen.Info.Template.for.PWA_UpdatesMay2023.docx)) the word "please" is removed.

2023-06-05 14:11 UTC, Gbarra9 commented on js/pages/samples.js
> +            'Monday - Thursday: 7:00 a.m. - 4:00 p.m. and Friday 7a.m. - noon',
Can you confirm this is the correct text? From the document I see `Monday – Thursday: 7:00 a.m. to 4:00 p.m. and Friday 7:00 a.m. to noon.` This is also the case for this [line 347](https://github.com/episphere/connectApp/pull/565/files#diff-086e163ff162b94330737cfb586d27c44a4871d7792612bf21d2791ead9d7c29R347)

2023-06-07 18:52 UTC, JoeArmani requested changes

2023-06-07 18:52 UTC, JoeArmani commented on js/pages/samples.js
> +    howToDonate: 'The email we send you will contain a link to schedule an appointment. Simply click the link to schedule a time that is convenient for you to donate your samples.You can also call Ma
It looks like we need a space between 'samples.' and 'You can'.
...`convenient for you to donate your samples. You can also call Marshfield`...

2023-06-09 16:25 UTC, JoeArmani commented on js/pages/samples.js
> +    howToDonate: 'The email we send you will contain a link to schedule an appointment. Simply click the link to schedule a time that is convenient for you to donate your samples.You can also call Ma
Looks good on this change, marking this resolved.

2023-06-09 16:39 UTC, Gbarra9 reviewed
Looks good. I added a minor suggestion.

2023-06-09 16:39 UTC, Gbarra9 commented on js/pages/samples.js
> +
Remove extra lines on line 361 and line 362.

2023-06-13 12:59 UTC, abhinavjonnada82 approved these changes

2023-06-13 13:35 UTC, Gbarra9 approved these changes
Looks good

2023-06-13 16:01 UTC, anthonypetersen approved these changes
looks good

2023-06-13 16:53 UTC, JoeArmani approved these changes
Looks good

2023-06-13 16:57 UTC, merged