#[563] Edit the descriptions of some surveys
episphere/connectApp pull request #607
Opened 2023-07-18 15:30 UTC by jhflorey

This PR addresses the issue https://github.com/episphere/connectApp/issues/563#issuecomment-1640419504

- Updated description of modules['Biospecimen Survey'] and modules['Clinical Biospecimen Survey'] in myToDoList.js`

2023-07-18 17:04 UTC, JoeArmani approved these changes
looks good

Will we be adding back the commente out code soon, or should it be removed?

2023-07-18 17:10 UTC, anthonypetersen requested changes

2023-07-18 17:10 UTC, anthonypetersen commented on js/pages/myToDoList.js
> +    // if(collections && collections.filter(collection => collection['650516960'] === 664882224).length > 0) {
why is this being commented out?

2023-07-19 13:11 UTC, jhflorey commented on js/pages/myToDoList.js
> +    // if(data['331584571']?.['266600170']?.['840048338']) {
Just for testing, my mistake.

2023-07-19 13:11 UTC, jhflorey commented on js/pages/myToDoList.js
> +    // if(collections && collections.filter(collection => collection['650516960'] === 664882224).length > 0) {
Just for testing, my mistake.

2023-07-19 14:01 UTC, anthonypetersen approved these changes
looks good

2023-07-19 14:12 UTC, merged