recreated content for myconnect
episphere/connectApp pull request #622
Opened 2023-08-03 18:41 UTC by ramavavi

The issue address is : https://github.com/episphere/connectApp/issues/419

The changes made in the code are:

1. Removed the api call for the functions and added the html and css to it. 
2.  Added responsiveness to the pages to look good in all the devices. 
3. Remove the extra spaces and adding alignment to the content.
4. Reducing the size of the images to fit properly.

2023-08-09 21:31 UTC, JoeArmani requested changes
The responsiveness looks good.
Checked:
√-About page
√-What to Expect page
√-Privacy page

General Issue 1:
I'm seeing quite a few CORS errors related to the Montserrat font from the new stylesheets that were imported. Have you noticed these? Will they be an issue?
<img width="664" alt="Screenshot 2023-08-09 at 5 18 48 PM" src="https://github.com/episphere/connectApp/assets/93854858/1056e5b0-b934-46da-9efb-b0a7768aecbc">
<img width="788" alt="Screenshot 2023-08-09 at 5 18 09 PM" src="https://github.com/episphere/connectApp/assets/93854858/c4ac79bf-508c-4b5f-8c00-303d37bb481e">

General Issue 2:
I noticed a Layout Shift (double loading) effect when loading About, What to Expect, and Privacy pages. First, you see the heading and two bullet points with no text. Then the page loads. What can be done about this? I think it could be detrimental to user experience. I double checked and this doesn't occur on the dev branch. When I commented out the newly added stylesheets, I see this (example of the double bullet points, but it doesn't get hidden):
<img width="1289" alt="Screenshot 2023-08-09 at 5 29 35 PM" src="https://github.com/episphere/connectApp/assets/93854858/f4251bca-24ea-4423-89cc-e07c256c883d">

General Issue 3:
Requesting changes on the code styling. Please format the entirety of:
`renderHomeAboutPage()`
`renderHomeExpectationsPage()`
`renderHomePrivacyPage()`
So that the code maintainable & extensible in the future. Here are a few screenshots of how the code looks on my end just in case it's an issue with how my import worked when I checked out your branch. If there are discrepancies on your end, please let me know.
<img width="1890" alt="Screenshot 2023-08-09 at 5 00 31 PM" src="https://github.com/episphere/connectApp/assets/93854858/ac1e1d76-fabd-4b17-bd71-b3edaba50c59">
<img width="1055" alt="Screenshot 2023-08-09 at 5 00 48 PM" src="https://github.com/episphere/connectApp/assets/93854858/43b2f819-b9a5-4d81-9a96-92ef46821753">
<img width="803" alt="Screenshot 2023-08-09 at 5 01 11 PM" src="https://github.com/episphere/connectApp/assets/93854858/39bb6d8a-cefa-4314-a37c-27720ce4aceb">

2023-08-09 21:31 UTC, JoeArmani commented on js/pages/homePage.js
please remove the console.log() ~line 652

2023-08-23 17:56 UTC, JoeArmani requested changes
additional comments on the unused bullet points that are rendering at the tops of a couple pages

2023-08-23 17:56 UTC, JoeArmani commented on js/pages/homePage.js
> +          </div>
remove this div. These are not in use and they're rendering as bullet points with no text. In the current format, this disappears when the stylesheet is fetched and loaded, but it is visible momentarily beforehand.

2023-08-23 17:56 UTC, JoeArmani commented on js/pages/homePage.js
> +            </div>
remove this div - same as above

2023-09-14 15:24 UTC, JoeArmani approved these changes
looks good.

Only remaining comments:
UX: Icons on the 'What to expect' page look a bit skewed (too tall). Maybe these can be resized?
UX: It might make sense to have the images appear without text alongside them in the smaller (<700px) view.

Both of the above are probably nitpicks, but I wanted to mention them.

2023-09-14 15:58 UTC, JoeArmani commented
> > looks good.
> > Only remaining comments: UX: Icons on the 'What to expect' page look a bit skewed (too tall). Maybe these can be resized? UX: It might make sense to have the images appear without text alongside them in the smaller (<700px) view.
> > Both of the above are probably nitpicks, but I wanted to mention them.
> 
> When I am trying to reduce the pixels the size of the image is reducing way to smaller so I left it as it is. I will re size the What to expect page images. Thank you.

Okay, just to reiterate: I don't think the images should be smaller in the mobile view. I just think the images should be on their own line (not alongside the text) in the mobile view. Thanks.

2023-09-20 17:47 UTC, anthonypetersen requested changes

2023-09-20 17:47 UTC, anthonypetersen commented on js/pages/homePage.js
> +signInBtn.addEventListener('click', async () => {
please fix the tabs on this section of code

2023-09-25 15:02 UTC, anthonypetersen approved these changes
looks good

2023-09-25 15:43 UTC, merged