[#537] Update participant signature
episphere/connectApp pull request #624
Opened 2023-08-07 16:02 UTC by jhflorey

2023-08-08 14:18 UTC, abhinavjonnada82 requested changes

2023-08-08 14:34 UTC, jhflorey commented on js/pages/agreements.js
> +    const suffix = data[693626233] || '';
Got it. Thanks @abhinavjonnada82 @jhflorey

2023-08-08 16:06 UTC, abhinavjonnada82 commented on js/pages/agreements.js
> +  const participantFullName = `${data[471168198]}${middleName}${data[736251808]} ${suffix}`;
` `${data[471168198]}${middleName}${data[736251808]} ${suffix}.trim()``

2023-08-08 16:26 UTC, jhflorey commented
@JoeArmani already updated and tested on my local.

2023-08-08 16:27 UTC, JoeArmani approved these changes
looks good

2023-08-09 19:23 UTC, anthonypetersen approved these changes
looks good

2023-08-10 14:02 UTC, merged