Added new location to HP Mysamples page.
episphere/connectApp pull request #666
Opened 2023-11-16 19:02 UTC by ramavavi

This PR addresses the issue: https://github.com/episphere/connect/issues/814

1. Added two new locations and scheduling information it the locations.
2. Added new subheading When Will I Receive My $25 Payment?
3. Added new information under How Should I Prepare On the Day of My Appointment?

2023-11-16 21:12 UTC, Gbarra9 requested changes

2023-11-16 21:12 UTC, Gbarra9 commented on js/pages/samples.js
> +    prepareInstructions: '<span class="site-info-bold">Connect Research Location:</span><br><br>On the day of your appointment, please drink plenty of water, but <span class="site-info-bold">stop dri
`<li>Make sure you know your login information for the MyConnect account.<li>`

Referring to the [document on box](https://nih.app.box.com/file/1361266398587?s=3po427g40hcw095qi6szfs4idji7ptn9): Should the text `MyConnect account` be a hyperlink?

2023-11-17 03:52 UTC, jhflorey approved these changes

2023-11-17 03:52 UTC, jhflorey commented
Looks good to me

2023-11-17 06:17 UTC, Gbarra9 approved these changes

2023-11-17 14:34 UTC, anthonypetersen approved these changes

2023-11-17 15:09 UTC, merged