[#1006] PROMIS Rollout to Backlog
episphere/connectApp pull request #824
Opened 2024-08-14 15:12 UTC by jhflorey

this PR address the issue https://github.com/episphere/connect/issues/1006

2024-08-14 15:24 UTC, anthonypetersen requested changes
see comment

2024-08-14 16:10 UTC, bransteitterbr approved these changes

2024-08-14 17:50 UTC, jhflorey commented
> see comment

@anthonypetersen which comment?

2024-08-15 16:39 UTC, jhflorey commented
> @jhflorey sorry, comment didn't save... please null check `verifiedTime`

Solved

2024-08-15 18:26 UTC, anthonypetersen approved these changes

2024-08-19 14:41 UTC, merged