[#994] Part 1: User Profile Enhancements for Intro and MyProfile page
episphere/connectApp pull request #854
Opened 2024-11-18 15:14 UTC by jhflorey

This PR addresses issue https://github.com/episphere/connect/issues/994

2024-11-18 15:41 UTC, bransteitterbr commented on i18n/en.js
> +        "birthPlaceIntroduction": "We collect this information so that we canmay match any information we collect from other sources, like state health registries, to you.",
Typo: canmay

2024-11-18 15:43 UTC, bransteitterbr commented on i18n/es.js
> +            "data-error-confirmation":"Spanish Text"
Placeholder text still present

2024-11-18 15:43 UTC, bransteitterbr commented on i18n/es.js
> +            "data-error-confirmation":"Spanish Text"
Placeholder text still present

2024-11-18 15:53 UTC, jhflorey commented on i18n/en.js
> +        "birthPlaceIntroduction": "We collect this information so that we canmay match any information we collect from other sources, like state health registries, to you.",
Solved

2024-11-18 22:06 UTC, JoeArmani requested changes
left comments

2024-11-19 14:32 UTC, jhflorey commented on js/components/form.js
> +                    <select style="margin-left:0px; max-width:188px;" id="UPMonthConfirmation" class="form-control confirmation-field" target="UPMonth" data-i18n="form.monthFieldConfirmation" data-er
@JoeArmani  we are still waiting for the final Spanish text to update all.
https://nih.app.box.com/integrations/officeonline/openOfficeOnline?fileId=1699379771757&sharedAccessCode=

2024-11-19 14:32 UTC, jhflorey commented on js/components/form.js
> +                    <select style="margin-left:0px; max-width:129px;" class="form-control confirmation-field" id="UPDayConfirmation" target="UPDay" data-i18n="form.dayFieldConfirmation" data-error-co
@JoeArmani  we are still waiting for the final Spanish text to update all.
https://nih.app.box.com/integrations/officeonline/openOfficeOnline?fileId=1699379771757&sharedAccessCode=

2024-11-19 14:32 UTC, jhflorey commented on js/components/form.js
> +                    <input data-i18n="form.yearListFieldConfirmation" style="margin-left:0px; max-width:170px;" type="text" class="form-control confirmation-field" id="UPYearConfirmation" Placeholder
@JoeArmani  we are still waiting for the final Spanish text to update all.
https://nih.app.box.com/integrations/officeonline/openOfficeOnline?fileId=1699379771757&sharedAccessCode=

2024-11-19 14:41 UTC, jhflorey commented
@JoeArmani @bransteitterbr we will have another PR for updating all the texts. Still waiting for the final specs
https://nih.app.box.com/integrations/officeonline/openOfficeOnline?fileId=1699379771757&sharedAccessCode=

2024-11-19 15:10 UTC, JoeArmani approved these changes

2024-11-19 17:44 UTC, bransteitterbr approved these changes

2024-11-20 14:04 UTC, merged